version: '3'
services:
  youtrack:
    image: jetbrains/youtrack:2019.1.52973
    container_name: youtrack
    ports:
      - 8080:8080
    volumes:
      - ./opt/youtrack/data:/opt/youtrack/data
      - ./opt/youtrack/conf:/opt/youtrack/conf
      - ./opt/youtrack/logs:/opt/youtrack/logs
      - ./opt/youtrack/backups:/opt/youtrack/backups 
    labels:
      - "traefik.enable=true"
      - "traefik.backend=server"
      - "traefik.frontend.rule=Host:${VIRTUAL_HOST}"
      - "traefik.docker.network=web"
      - "traefik.port=8080"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

        #  hub:
        #    image: jetbrains/hub:2019.1.12017
        #    container_name: hub
